name: Build

on:
  workflow_dispatch:
  push:
    branches: [master, develop, release]
  pull_request:
    branches: [master, develop, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: cat file
          uses: ./github/workflows/_cat_file.yml
